// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVt2ladY7I3Rg8NYb8z1Rn3KZasK6_yyw',
    appId: '1:126405216893:web:135c7113ff5e4624077f14',
    messagingSenderId: '126405216893',
    projectId: 'ayotaxy-8cd61',
    authDomain: 'ayotaxy-8cd61.firebaseapp.com',
    databaseURL: 'https://ayotaxy-8cd61-default-rtdb.firebaseio.com',
    storageBucket: 'ayotaxy-8cd61.firebasestorage.app',
    measurementId: 'G-0FMHSGDL30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTQ5V-tBUVGLYzSI0o_JpV-LyIakFkxHA',
    appId: '1:126405216893:android:d429da1f0bf4e3a6077f14',
    messagingSenderId: '126405216893',
    projectId: 'ayotaxy-8cd61',
    databaseURL: 'https://ayotaxy-8cd61-default-rtdb.firebaseio.com',
    storageBucket: 'ayotaxy-8cd61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA881kp27lVkPIrPyFX0OjZQ1RQ2umEPP0',
    appId: '1:126405216893:ios:f0e81202b9c2412f077f14',
    messagingSenderId: '126405216893',
    projectId: 'ayotaxy-8cd61',
    databaseURL: 'https://ayotaxy-8cd61-default-rtdb.firebaseio.com',
    storageBucket: 'ayotaxy-8cd61.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA881kp27lVkPIrPyFX0OjZQ1RQ2umEPP0',
    appId: '1:126405216893:ios:f0e81202b9c2412f077f14',
    messagingSenderId: '126405216893',
    projectId: 'ayotaxy-8cd61',
    databaseURL: 'https://ayotaxy-8cd61-default-rtdb.firebaseio.com',
    storageBucket: 'ayotaxy-8cd61.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVt2ladY7I3Rg8NYb8z1Rn3KZasK6_yyw',
    appId: '1:126405216893:web:fdcf47f7af26fa7b077f14',
    messagingSenderId: '126405216893',
    projectId: 'ayotaxy-8cd61',
    authDomain: 'ayotaxy-8cd61.firebaseapp.com',
    databaseURL: 'https://ayotaxy-8cd61-default-rtdb.firebaseio.com',
    storageBucket: 'ayotaxy-8cd61.firebasestorage.app',
    measurementId: 'G-0W3HSCYCL4',
  );
}
